version: '3.8'

services:
  wsrecord:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'      # عيش ازبي 
          memory: 2G        # 2تخخدم ولا نحويك ؟
    restart: always
    env_file:
      - .env
